Code modifications to use env parameters instead of hardcoded.
lbadmin/vendo-sdk-php pull request #15
Opened 2023-04-24 10:05 UTC by pwolowiec-zz

New bash script that load selected parameters and runs example script. Added docker for that test.

2023-04-25 10:00 UTC, zbigniewwiech requested changes

2023-04-25 10:01 UTC, zbigniewwiech commented on examples/subscription/cancel-subscription.php
> +    $cancel->setMerchantId(getenv('MERCHANT_ID'));//Your Vendo Merchant ID
not 100% sure. it's all for the merchant's convenience

2023-04-25 11:18 UTC, pwolowiec-zz commented on readme-dev.md
> +`  docker-compose up --build -d`
Linux habit :-). It's oryginaly was with dash, and in fact still works that way :-)

2023-05-04 10:30 UTC, zbigniewwiech approved these changes

2023-05-04 10:30 UTC, merged